name = "go-auth"
main = "src/index.js"
compatibility_date = "2025-05-28"
compatibility_flags = ["nodejs_compat"] # Fix for Node.js built-in modules
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "go-auth"
database_id = "f6100f31-4a5d-4005-ba82-2b2e22eee355"

[[kv_namespaces]]
binding = "KV"
id = "b619d313838340b5921e0bf8e492799f"

JWT_SECRET= "123bc901ad1260cc***"

[observability.logs]
enabled = true



