name = "go-auth"
main = "src/index.js"
compatibility_date = "2025-05-28"
compatibility_flags = ["nodejs_compat"] # Fix for Node.js built-in modules
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "go-auth"
database_id = ""

[[kv_namespaces]]
binding = "KV"
id = ""

[observability.logs]
enabled = true



